[mypy]
python_version = 3.13
ignore_missing_imports = True
warn_unused_ignores = False
strict_optional = False

[mypy-tests.*]
ignore_errors = True

[mypy-app.db.models.*]
ignore_errors = True

[mypy-tools.*]
ignore_errors = True

[mypy-app.main]
ignore_errors = True