"""baseline_schema

Revision ID: 80f5b3e9fd12
Revises:
Create Date: 2026-03-27 14:58:12.648279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80f5b3e9fd12"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique audit event identifier."
        ),
        sa.Column(
            "event_type",
            sa.String(length=64),
            nullable=False,
            comment="Event type identifier.",
        ),
        sa.Column(
            "entity_type",
            sa.String(length=32),
            nullable=False,
            comment="Entity type (e.g., trip).",
        ),
        sa.Column(
            "entity_id",
            sa.String(length=64),
            nullable=False,
            comment="Entity identifier as string.",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Serialized event payload.",
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when event occurred.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Persistence timestamp.",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_events_entity",
        "audit_events",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_occurred_at", "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "interaction_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("trip_id", sa.String(length=36), nullable=True),
        sa.Column("previous_state", sa.String(length=32), nullable=True),
        sa.Column("new_state", sa.String(length=32), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("payment_status", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interaction_logs_timestamp"),
        "interaction_logs",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_logs_trip_id"),
        "interaction_logs",
        ["trip_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_logs_user_id"),
        "interaction_logs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "otp_codes",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique OTP request identifier."
        ),
        sa.Column(
            "phone",
            sa.String(length=32),
            nullable=False,
            comment="Phone number used for OTP.",
        ),
        sa.Column(
            "code_hash",
            sa.String(length=128),
            nullable=False,
            comment="Hashed OTP code.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="OTP expiration timestamp.",
        ),
        sa.Column(
            "consumed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when OTP was used.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation timestamp.",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_otp_codes_phone"), "otp_codes", ["phone"], unique=False)
    op.create_index(
        "ix_otp_codes_phone_expires", "otp_codes", ["phone", "expires_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique user identifier."),
        sa.Column(
            "role",
            sa.Enum("passenger", "driver", "admin", name="role_enum"),
            nullable=False,
            comment="Active role for permissions.",
        ),
        sa.Column(
            "name", sa.String(length=120), nullable=False, comment="Display name."
        ),
        sa.Column(
            "phone",
            sa.String(length=32),
            nullable=False,
            comment="Phone number used for OTP login.",
        ),
        sa.Column(
            "status",
            sa.Enum("active", "blocked", "pending", name="user_status_enum"),
            nullable=False,
            comment="Account status.",
        ),
        sa.Column(
            "requested_role",
            sa.String(length=32),
            nullable=True,
            comment="BETA: passenger or driver — role requested at signup.",
        ),
        sa.Column(
            "avg_rating_as_passenger",
            sa.Numeric(precision=3, scale=2),
            nullable=True,
            comment="Average rating from drivers (1-5).",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated on state changes or profile edits.",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_index("ix_users_role_status", "users", ["role", "status"], unique=False)
    op.create_table(
        "drivers",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="User identifier for the driver profile.",
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="driver_status_enum"),
            nullable=False,
            comment="Driver approval status.",
        ),
        sa.Column(
            "documents",
            sa.Text(),
            nullable=True,
            comment="Document references or URLs.",
        ),
        sa.Column(
            "commission_percent",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            comment="Commission percentage for this driver.",
        ),
        sa.Column(
            "is_available",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="True when driver can accept new trips.",
        ),
        sa.Column(
            "cancellation_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Number of trips cancelled by this driver (penalty tracking).",
        ),
        sa.Column(
            "avg_rating",
            sa.Numeric(precision=3, scale=2),
            nullable=True,
            comment="Average rating from passengers (1-5).",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated on approval or contract changes.",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("ix_drivers_status", "drivers", ["status"], unique=False)
    op.create_table(
        "driver_locations",
        sa.Column(
            "driver_id",
            sa.UUID(),
            nullable=False,
            comment="Driver user_id (matches drivers.user_id).",
        ),
        sa.Column(
            "lat",
            sa.Numeric(precision=9, scale=6),
            nullable=False,
            comment="Last latitude reported by driver.",
        ),
        sa.Column(
            "lng",
            sa.Numeric(precision=9, scale=6),
            nullable=False,
            comment="Last longitude reported by driver.",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of last location update.",
        ),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("driver_id"),
    )
    op.create_index(
        "ix_driver_locations_driver_id", "driver_locations", ["driver_id"], unique=False
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique trip identifier."),
        sa.Column(
            "passenger_id",
            sa.UUID(),
            nullable=False,
            comment="Passenger user identifier.",
        ),
        sa.Column(
            "driver_id",
            sa.UUID(),
            nullable=True,
            comment="Assigned driver identifier (nullable until accepted).",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "assigned",
                "accepted",
                "arriving",
                "ongoing",
                "completed",
                "cancelled",
                "failed",
                name="trip_status_enum",
            ),
            nullable=False,
            comment="Lifecycle status of the trip.",
        ),
        sa.Column(
            "origin_lat",
            sa.Numeric(precision=9, scale=6),
            nullable=False,
            comment="Origin latitude.",
        ),
        sa.Column(
            "origin_lng",
            sa.Numeric(precision=9, scale=6),
            nullable=False,
            comment="Origin longitude.",
        ),
        sa.Column(
            "destination_lat",
            sa.Numeric(precision=9, scale=6),
            nullable=False,
            comment="Destination latitude.",
        ),
        sa.Column(
            "destination_lng",
            sa.Numeric(precision=9, scale=6),
            nullable=False,
            comment="Destination longitude.",
        ),
        sa.Column(
            "estimated_price",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Estimated price at request time.",
        ),
        sa.Column(
            "distance_km",
            sa.Numeric(precision=8, scale=2),
            nullable=True,
            comment="Trip distance in km (null until known or mocked).",
        ),
        sa.Column(
            "duration_min",
            sa.Numeric(precision=8, scale=2),
            nullable=True,
            comment="Trip duration in minutes (null until known or mocked).",
        ),
        sa.Column(
            "final_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Final price after completion.",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the trip was started by the driver.",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the trip was marked as completed.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated on state transitions or price updates.",
        ),
        sa.Column(
            "cancellation_reason",
            sa.String(length=280),
            nullable=True,
            comment="Reason for cancellation, when cancelled.",
        ),
        sa.Column(
            "cancellation_fee",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Fee charged when passenger cancels after driver accepted.",
        ),
        sa.Column(
            "cancelled_by",
            sa.String(length=16),
            nullable=True,
            comment="Who cancelled: passenger, driver, admin.",
        ),
        sa.Column(
            "driver_rating",
            sa.Integer(),
            nullable=True,
            comment="Passenger's rating of driver (1-5), set after completion.",
        ),
        sa.Column(
            "passenger_rating",
            sa.Integer(),
            nullable=True,
            comment="Driver's rating of passenger (1-5), set after completion.",
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"], ["drivers.user_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["passenger_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trips_driver_id", "trips", ["driver_id"], unique=False)
    op.create_index("ix_trips_passenger_id", "trips", ["passenger_id"], unique=False)
    op.create_index("ix_trips_status", "trips", ["status"], unique=False)
    op.create_table(
        "payments",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique payment identifier."
        ),
        sa.Column(
            "trip_id", sa.UUID(), nullable=False, comment="Associated trip identifier."
        ),
        sa.Column(
            "total_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Total charged amount.",
        ),
        sa.Column(
            "commission_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Platform commission amount.",
        ),
        sa.Column(
            "driver_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Driver share from authorization (legacy; driver_payout is final).",
        ),
        sa.Column(
            "driver_payout",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Final driver payout at completion (pricing engine). Future: deprecate driver_amount.",
        ),
        sa.Column(
            "stripe_payment_intent_id",
            sa.String(length=128),
            nullable=True,
            comment="Stripe PaymentIntent identifier, when available.",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default="EUR",
            nullable=False,
            comment="ISO currency code (e.g., EUR).",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "succeeded",
                "failed",
                name="payment_status_enum",
            ),
            nullable=False,
            comment="Payment status.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated on payment status changes.",
        ),
        sa.Column(
            "authorization_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Stripe authorization expiration timestamp, if available.",
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stripe_payment_intent_id", name="unique_stripe_payment_intent_id"
        ),
        sa.UniqueConstraint("trip_id", name="uq_payments_trip_id"),
    )
    op.create_table(
        "trip_offers",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique offer identifier."),
        sa.Column(
            "trip_id", sa.UUID(), nullable=False, comment="Trip this offer is for."
        ),
        sa.Column(
            "driver_id",
            sa.UUID(),
            nullable=False,
            comment="Driver who received this offer.",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "accepted", "rejected", "expired", name="offer_status_enum"
            ),
            server_default="pending",
            nullable=False,
            comment="Offer status.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the offer expires.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation timestamp.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Updated on status change.",
        ),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trip_offers")
    op.drop_table("payments")
    op.drop_index("ix_trips_status", table_name="trips")
    op.drop_index("ix_trips_passenger_id", table_name="trips")
    op.drop_index("ix_trips_driver_id", table_name="trips")
    op.drop_table("trips")
    op.drop_index("ix_driver_locations_driver_id", table_name="driver_locations")
    op.drop_table("driver_locations")
    op.drop_index("ix_drivers_status", table_name="drivers")
    op.drop_table("drivers")
    op.drop_index("ix_users_role_status", table_name="users")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_otp_codes_phone_expires", table_name="otp_codes")
    op.drop_index(op.f("ix_otp_codes_phone"), table_name="otp_codes")
    op.drop_table("otp_codes")
    op.drop_index(op.f("ix_interaction_logs_user_id"), table_name="interaction_logs")
    op.drop_index(op.f("ix_interaction_logs_trip_id"), table_name="interaction_logs")
    op.drop_index(op.f("ix_interaction_logs_timestamp"), table_name="interaction_logs")
    op.drop_table("interaction_logs")
    op.drop_index("ix_audit_events_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
